# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
project 'WizCart Test.xcodeproj'

target 'WizCart-Test' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WizCart-Test

  pod 'WizCart', '~> 1.5.6'
  pod 'Alamofire'
  
  target 'WizCart-TestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WizCart-TestUITests' do
    # Pods for testing
  end

end
